version: '3'

services:
    docker-registry:
        container_name: pvt-registry.io
        image: registry:2
        ports:
            - 5000:5000
        restart: always
        volumes:
            - /mnt/registry:/var/lib/registry
            - ./auth:/auth
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

    docker-registry-ui:
        container_name: pvt-private-registry-ui
        image: konradkleine/docker-registry-frontend:v2
        ports:
            - 8080:80
        restart: always
        environment:
            ENV_DOCKER_REGISTRY_HOST: pvt-registry.io
            ENV_DOCKER_REGISTRY_PORT: 5000
        extra_hosts:
             - "tp-registry.io:XXX.XXX.YYY.YYY"
