version: "2.5"
services:
  docker-registry:
    image: registry:latest
    container_name: pvt-registry.io
    ports:
    - 5000:5000
    restart: always
    volumes:
    - ./docker-registry:/var/lib/registry

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: pvt-registry-ui
    ports:
    - 8080:80
    restart: always
    environment:
      ENV_DOCKER_REGISTRY_HOST: pvt-registry.io
      ENV_DOCKER_REGISTRY_PORT: 5000
    extra_hosts:
         - "pvt-registry.io:<XXX.XXX.YYY.YYY>"
